### PR TITLE
Added fs.read functionality

### PR DESCRIPTION
**Pull request by imsnif**
Should behave exactly like node's fs.read (including partial reads into buffer, offsets within given buffer, etc.)
If I missed anything, please let me know.

### CODE REVIEW

**Comment by mmckegg** [comment]
@imsnif: When I tried this, the test didn't seem to be passing. The buffer ends up being empty.

I have added you as a collaborator, so you're welcome to go ahead and merge this pull request and the other ones too. Let me know once that's done, and I'll publish a new version.

**Comment by imsnif** [comment]
Fixed.
My apologies, I had environment issues with testling so the tests were passing for me using: ````browserify test/test.js | testling````
Odd. Working both ways now (and also inside a chrome-app).
I'll merge this and the rest a little later today.

**Comment by imsnif** [comment]
@mmckegg: I've merged everything, and updated the readme. Feel free to update npm.

P.S.
I did not mention - this package saved me incredible anguish and a lot of time. I really appreciate it.

**Comment by mmckegg** [comment]
@imsnif: Glad to hear :smile: I'm not actually using this module personally anymore (used to use it in a chrome app, but now I'm using electron), so it's nice to get some fresh eyes on it!

All published as **v2.0.0** --- there were a few things that _possibly_ could have been breaking, so just playing it safe.

**Pull request merged**
